name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    services:
          mysql:
            image: mysql:8.0
            env:
              MYSQL_DATABASE: laravel
              MYSQL_ROOT_PASSWORD: password
            ports:
              - 3306
            options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.hook', '.env');"
    - name: Install Dependencies
      run: composer update && composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        MYSQL_HOST: 127.0.0.1
        MYSQL_DATABASE: laravel
        MYSQL_USERNAME: root
        MYSQL_PASSWORD: password
        MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
      run: vendor/bin/phpunit
